# Render Blueprint pour SportPool
# Configuration pour déploiement sur Render.com
services:
  # Service Web principal (Backend Express + Frontend servi)
  - type: web
    name: sportpool-app
    plan: starter # gratuit, peut être upgrade vers paid plans
    env: node
    region: frankfurt # ou oregon selon vos préférences
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sportpool-db
          property: connectionString
      - key: SENDGRID_API_KEY
        sync: false # sera configuré manuellement via dashboard
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: SENDGRID_FROM_NAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true # Render génère automatiquement une valeur sécurisée
      - key: APP_URL
        value: https://sportpool.onrender.com
    buildFilter:
      paths:
        - server/**
        - client/**
        - shared/**
        - package.json
        - package-lock.json
        - vite.config.ts
        - tailwind.config.ts
    
# Base de données PostgreSQL
databases:
  - name: sportpool-db
    databaseName: sportpool
    user: sportpool_user
    plan: free # PostgreSQL gratuit jusqu'à 1GB
    region: frankfurt